// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCitasMedicas.Data;

#nullable disable

namespace SistemaCitasMedicas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624150957_ModificacionHorarioMedicos")]
    partial class ModificacionHorarioMedicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaCitasMedicas.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<DateOnly>("FechaCita")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdEstadoCita")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdCita");

                    b.HasIndex("IdEstadoCita");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.HasIndex("IdMedico", "FechaCita");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.EstadoCita", b =>
                {
                    b.Property<int>("IdEstadoCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCita"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoCita");

                    b.ToTable("EstadosCita");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.EstadoSolicitud", b =>
                {
                    b.Property<int>("IdEstadoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoSolicitud"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoSolicitud");

                    b.ToTable("EstadosSolicitud");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.HistorialSolicitud", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<int?>("MedicoIdMedico")
                        .HasColumnType("int");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex("MedicoIdMedico");

                    b.ToTable("HistorialesSolicitud");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.HorarioMedico", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdMedico", "DiaSemana");

                    b.HasIndex("IdMedico", "DiaSemana", "HoraInicio", "HoraFin")
                        .IsUnique();

                    b.ToTable("HorariosMedico");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Medico", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedico"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionCitaMin")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NumeroLicencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMedico");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.HasIndex("NumeroLicencia")
                        .IsUnique();

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.SolicitudCita", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("ComentarioRespuesta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("FechaDeseada")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraDeseada")
                        .HasColumnType("time");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdEstadoSolicitud");

                    b.HasIndex("IdPaciente");

                    b.ToTable("SolicitudesCita");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Cita", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("IdEstadoCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.Medico", "Medico")
                        .WithMany("Citas")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.SolicitudCita", "Solicitud")
                        .WithOne("Cita")
                        .HasForeignKey("SistemaCitasMedicas.Models.Cita", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("Medico");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.HistorialSolicitud", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.SolicitudCita", "Solicitud")
                        .WithMany("Historiales")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.Medico", "Medico")
                        .WithMany("Historiales")
                        .HasForeignKey("MedicoIdMedico");

                    b.Navigation("Medico");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.HorarioMedico", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.Medico", "Medico")
                        .WithMany("Horarios")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Medico", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.Especialidad", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.Usuario", "Usuario")
                        .WithOne("Medico")
                        .HasForeignKey("SistemaCitasMedicas.Models.Medico", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Paciente", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.Usuario", "Usuario")
                        .WithOne("Paciente")
                        .HasForeignKey("SistemaCitasMedicas.Models.Paciente", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.SolicitudCita", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.Especialidad", "Especialidad")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.EstadoSolicitud", "EstadoSolicitud")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEstadoSolicitud")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitasMedicas.Models.Paciente", "Paciente")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("EstadoSolicitud");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Usuario", b =>
                {
                    b.HasOne("SistemaCitasMedicas.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.EstadoSolicitud", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Medico", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Historiales");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Paciente", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.SolicitudCita", b =>
                {
                    b.Navigation("Cita");

                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("SistemaCitasMedicas.Models.Usuario", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
